<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes - Generated by Vemto
|--------------------------------------------------------------------------
|
| It is not recommended to edit this file directly. Although you can do so,
| it will generate a conflict on Vemto's next build.
|
*/

// Dashboard
Route::prefix('/dashboard')
    ->name('dashboard.')
    ->middleware(['auth:sanctum', config('jetstream.auth_session'), 'verified'])
    ->group(function () {
        Route::get(
            '/suppliers',
            App\Livewire\Dashboard\SupplierIndex::class
        )->name('suppliers.index');

        Route::get(
            '/suppliers/create',
            App\Livewire\Dashboard\SupplierCreate::class
        )->name('suppliers.create');

        Route::get(
            '/suppliers/{supplier}',
            App\Livewire\Dashboard\SupplierEdit::class
        )->name('suppliers.edit');
    });

// API
Route::prefix('/api')
    ->name('api.')
    ->middleware(['auth:sanctum', config('jetstream.auth_session'), 'verified'])
    ->group(function () {});

// Site
Route::prefix('/')->group(function () {});

// Filament Panel
Route::prefix('/panel')
    ->name('panel.')
    ->group(function () {});
